let stack = [];
stack.push(1);
stack.push(2);
stack.push(3);
stack.push(4);
stack.push(5);
let topStack = stack.pop();
let peekTopStack = stack[stack.length -1];
console.log(peekTopStack);
console.log(topStack);
console.log(stack);